#!/bin/bash
#This script runs git commands to push to remote repository

echo "please enter a commit message"
read commit_message
git add -A
git commit -m "$commit_message"
git push

echo "Push successful with commit message as: $commit_message"
